language: node_js
os:
  - linux
node_js:
  - '10'
  - '12'
cache:
  yarn: true
before_install:
  - npm install -g yarn
install:
  - yarn install
  - yarn test
  # list installed react and react-dom packages
  - yarn list --silent react react-dom
script:
  - yarn build
  - yarn eslint
after_success: 
  - cp -af packages/styled-docs/docs packages/styled-docs/git-pages/
deploy:
  provider: pages:git
  repo: joshuatai/test
  token:
    secure: "fb399206bfda3dd9f8fb07e5a17afad82f5d9ae1"
  edge: true # dpl v2
  keep_history: true
  target_branch: gh-pages
  local_dir: "packages/styled-docs/git-pages"
  # on:
  #   branch: dev
  #   node: '10'
# notifications:
#   slack:
#     secure: dPF2omw9ykWqJ2C9kV8yq67zJVyezt58kmnRHavrq1+U1e5tDZootxoMjwMzq/T3pctghLbE4QYtg4s3GxINP5mMLMKLoUjDqsnFijKXB9jInWdbxFcDi0pY1w3KimEgSUWd5UZS6WWH23mPGO923KKhu3FE0jnISNlpV6/HQAiAgokMYEMC3Sx9V37iUQsnVBpshhEHMXbK6s9kp6H1gmmfPNuqnSJN0PQ9OaRKlUOlbFjgahFJdljG/TG1qeeGGxUzGu+r1tBmsfsjSqgWbcRDNfHpkx1PeelyhorsA6/CMBW82tVAGA5Z03nw0USrETG8vqPm/B6nnAa+vCvXaUxeft0R75Dczmx9FqGNygyrIwbtxjel5BQCYovVxjkHDniOhd7n0I7c97aXkaaJTvSV2CRSt7DmOPiNE+6mqBaEh9f7OfjsTA8/nShsaVQ5DQAuGfxsSjRTDuJY5NGjBgfIF/2nT2gS1cS/QQza6HcijaOWKTRCgT6/PC++oNTTy6FK1H7epYe41HmIYCDF/Urk1k+DlmCSbshdIGRg05anuTLqCPi6Tz7fFKNNzY4uuB6315vDgKOI91JTIM+5QBCgxjm09E2eIiEpZgIEicvjs1CKZIsfi9R1HgkWD+mngcJvYApwQ+qwvdV/L+zLUkWR9ifz3uFIFtssK30OWQ8=
