language: node_js
os:
- linux
node_js:
- '10'
- '12'
cache:
  yarn: true
before_install:
- npm install -g yarn
install:
- yarn install
- yarn test
- yarn list --silent react react-dom
script:
- yarn build
- yarn eslint
after_success:
- cp -af packages/styled-docs/docs packages/styled-docs/git-pages/
deploy:
  provider: pages:git
  token:
    secure: XWgIUW6q4usFDjM0WeQPA2j//dvhWXKGKuDOjJznOgLgcUnJPI8zdyKoNcycdYxp4RU1Sf5y5DVenBs9Wjp4zbT1V+M9smtPrVBUdEi0wjuwZEfWXF2vVUcD3Nqe9CmKS0SHm+IkhUN1jtZdD4nVAtpXtLJq/PuUzt1TuMUd5yAUlmvV2ylei5cTKdCAI6kvRluvZJXMhalTMeZP74I8+9m8U3+y+1xtEOxzvchaX8xwblB0gCglDy71fEXv6B+Ut8jSpiUv60gvq6w12TNpwSfzN8pZCe8LCZ2qT/7q955x0HbrFIf8thwvvNLNKwXm65Ccoljns1LPaM9e9Nern44Z4Fh1hooBqTxtT8Dm0Gqa8GwxWmcwAkNT10aEl4yUv5ilnkRSkYZ6eynWTQmHhFwd5icipyZMVw5w0DxPKbWEX250CV3bfzKPn8i79r1eiLU+FDCKrfDplTTSFt9CnY938u9FR8b8cR6Q2w3Vz5flZzyTmAivKXbBYcR/TCfkOZ5ApNDHsAuU4KEUXl0wqZ5SHs9envWKSCiHO0ndS+d2Xtj/v1FC9xvYjyCbnc2Z4IiCM3/e6n7dfZlg5cUgZQp+tgSoO5FAhV4kEaBmkKT6jusLx6zBJU0S/1WFik/8Z2t0HNluFzH9T/RnN9xsj2ioTMOEoxHz1gSuefgdak8=
  edge: true
  keep_history: true
  target_branch: gh-pages
  local_dir: packages/styled-docs/git-pages
  on:
    branch: master
    node: '10'

